### ISSUE TITLE
Create new content type - Static Page

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#10]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Static Page | spag | Title | Default |   | node |   | Y |  
Static Page | spag | Body | Long text, formatted |   |   |   |   |  
Static Page | spag | Hero | Entity reference to hero |   |   |   |   |

**Comment by Mercergirl** [comment]
Done except entity reference. Needs research.

**Comment by Mercergirl** [comment]
Done.

**Comment by shaal** [comment]
The machine name of content types - should follow the Relativity method
(spag)
(please see https://github.com/iribarne/broward-drupal/issues/43 for more details)

**Comment by Mercergirl** [comment]
Done.
