### ISSUE TITLE
Create new content type - Hero

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#11]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Hero | hero | Title | Default |   | node | Front block view |   |  
  |   | Teaser Snippet | Plain text | 255 |   |   |   |  
  |   | Link | Link |   |   |   |   |  
  |   | Image |   |   |   |   |   |

**Comment by Mercergirl** [comment]
Done except for entity reference to image. Needs research.

**Comment by shaal** [comment]
What research is needed for image?

**Comment by Mercergirl** [comment]
Research for entity reference. I got it now, I think? I created the image as a reference to content field type so it could be an entity reference. I thought I would create it as an entity reference type, but maybe I am wrong?

**Comment by Mercergirl** [comment]
@shaal @jeppy64 Can someone please check the Hero content type to see if I created the Image field correctly. I am not sure about the Field Type being Entity Reference, it was supposed to be Image, but that didn't seem to work out for other content types that needed to use the Hero Image as Entity Reference. Thanks

http://dev-relativity-event-management.pantheonsite.io/admin/structure/types/manage/hero/fields

**Comment by shaal** [comment]
Under "Reference", you will find "Image", that's how that field should be.

![image](https://user-images.githubusercontent.com/22901/31048734-abeddc90-a5f1-11e7-91b8-572d933decc5.png)

**Comment by Mercergirl** [comment]
All done.
