### ISSUE TITLE
Create new content type - Card

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#12]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Card | card | Title | Default |   | node | Front block view |   |  
  |   | Teaser Snippet | Plain text | 255 |   |   |   |  
  |   | Link | Link |   |   |   |   |  
  |   | Image |   |   |   |   |   |

**Comment by Mercergirl** [comment]
Done!
