### ISSUE TITLE
Create new content type - News

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#13]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
News | news | Title | Default |   | node | Front block view |   | ntyp
  |   | Body | Long text, formatted |   |   |   |   |  
  |   | Type | Taxonomy entity reference |   |   |   |   |

**Comment by jeppy64** [comment]
Easiest way is to follow the base table machine name for fields that aren't entity references.

Example:
Content Type = News
machine name = news
Body = news_body
Type = news_ntyp_ref

**Comment by cjgratacos** [comment]
News Content Type Field Machine Names:
- Body: field_news_body
- Type: field_news_ntyp_ref

**Comment by jeppy64** [comment]
Type is an entity reference out to a taxonomy as shown in the table, so for this field it would be:

news_ntyp_ref
