### ISSUE TITLE
Create new content type - Event

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#14]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Event | even | Title | Default |   | node | Upcoming events |   |  
  |   | Body | Long text, formatted |   |   |   |   |  
  |   | Event Day | Entity reference to eday |   |   |   |   |  
  |   | Featured Speaker | Entity reference to fspk |   |   |   |   |  
  |   | Schedule Item | Entity reference to sitm |   |   |   |   |  
  |   | Sponsor | Entity reference to spon |   |   |   |   |  
  |   | Time Slot | Entity reference to tslo |   |   |   |   |  
  |   | Venue | Entity reference to venu |   |   |   |   |  
  |   | Image Gallery | Entity reference to igal |   |   |   |   |

**Comment by ghost** [comment]
Good afternoon @Solamsnake - ok to close this issue or is any additional work needed?

**Comment by ghost** [comment]
Done ! But I noticed 2 things during I was completing my task.

First the machine name for the content type "Event Day" is wrong... it must be "eday"  and not "event_day". Second, the machine name for "Venue" must be "venu" and not "venue".

Even if the machine names for these content types were wrong, I created the good machine name for my entity reference fields.

@betheas I just worked 10 minutes for this task.

**Comment by ghost** [comment]
Ho and I forgot, the machine name for static page is wrong also lol must be "spag" and not "static_page"

**Comment by shaal** [comment]
The other content types should be good now

**Comment by ghost** [comment]
Ok done
