### ISSUE TITLE
Create new content type - Event Day

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#15]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Event Day | eday | Title | Default |   | node | Day of event within event |   |  
  |   | Date | Date only |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by Mercergirl** [comment]
Done!

**Comment by shaal** [comment]
The machine name of content types - should follow the Relativity method
(eday)
(please see https://github.com/iribarne/broward-drupal/issues/43 for more details)

**Comment by Mercergirl** [comment]
Done.
