### ISSUE TITLE
Create new content type - Time Slot

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#16]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Time Slot | tslo | Title | Default |   | node |   |   |  
  |   | Start Hour | List text (1-12) |   |   |   |   |  
  |   | Start Minute | List text (0-55) by 5 |   |   |   |   |  
  |   | Start Meridiem | List text AM-PM |   |   |   |   |  
  |   | End Hour | List text (1-12) |   |   |   |   |  
  |   | End Minute | List text (0-55) by 5 |   |   |   |   |  
  |   | End Meridiem | List text AM-PM |   |   |   |   |

**Comment by ghost** [comment]
Content type created
