### ISSUE TITLE
Create new content type - Featured Speaker

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#17]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Featured Speaker | fspk | First Name | Plain text |   | user |   |   |  
  |   | Middle Initial | Plain text |   |   |   |   |  
  |   | Last Name | Plain text |   |   |   |   |  
  |   | Company | Plain text |   |   |   |   |  
  |   | Work Title | Plain text |   |   |   |   |  
  |   | Email | Email |   |   |   |   |  
  |   | Drupal Profile Link | Link |   |   |   |   |  
  |   | Twitter Profile Link | Link |   |   |   |   |  
  |   | Website Link | Link |   |   |   |   |  
  |   | Portrait | Image |   |   |   |   |  
  |   | Bio | Long text, formatted |   |   |   |   |

**Comment by ghost** [comment]
Content type created
