### ISSUE TITLE
Create new content type - Venue

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#18]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Venue | venu | Title | Default |   | node | location of event |   |  
  |   | Body | Long text, formatted |   |   |   |   |  
  |   | GMAP Location | Plain text |   |   |   |   |  
  |   | Hero | Entity reference hero |   |   |   |   |  
  |   | Phone | Phone |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by Mercergirl** [comment]
Done except for entity reference.

**Comment by Mercergirl** [comment]
Done.

**Comment by shaal** [comment]
The machine name of content types - should follow the Relativity method
(venu)
(please see https://github.com/iribarne/broward-drupal/issues/43 for more details)

**Comment by Mercergirl** [comment]
Done.
