### ISSUE TITLE
Create new content type - Session

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#19]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Session | sess | Title | Default |   | node |   |   |  
  |   | Body | Long text, formatted |   |   |   |   |  
  |   | Slide Deck | File Upload |   |   |   |   |  
  |   | Presenter | Entity Reference to atte |   |   |   |   |  
  |   | Status | List text (proposed-accepted) |   |   |   |   |  
  |   | Track | Taxonomy Term Reference |   |   |   |   |  
  |   | Audience | Taxonomy Term Reference |   |   |   |   |  
  |   | Document | Entity Reference to docu |   |   |   |   |

**Comment by cjgratacos** [comment]
Done
