### ISSUE TITLE
Create new content type - Attendee

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#20]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Attendee | atte | Title | Default |   | node |   |   |  
  |   | Body | Long text, formatted |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by ghost** [comment]
Content type created
