### ISSUE TITLE
Create new content type - Schedule Item

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#21]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Schedule Item | sitm | Title | Default |   | node |   |   |  
  |   | Time Slot | Entity reference to tslo |   |   |   |   |  
  |   | Session | Entity reference to sess |   |   |   |   |

**Comment by cjgratacos** [comment]
Done
