### ISSUE TITLE
Create new content type - Sponsor

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#22]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Sponsor | spon | Title | Default |   | node |   |   |  
  |   | Body | Long text, formatted |   |   |   |   |  
  |   | Sponsor Level | Taxonomy Term Reference |   |   |   |   |  
  |   | Logo | Image |   |   |   |   |  
  |   | Website Link | Link |   |   |   |   |

**Comment by cjgratacos** [comment]
Done
