### ISSUE TITLE
Create new content type - Venue Room

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#23]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Venue Room | vroo | Title | Default |   | node |   |   |  
  |   | Building / Room | Plain text |   |   |   |   |  
  |   | Capacity | Integer |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by cjgratacos** [comment]
Venue Room Fields Machine Name:
-  Building / Room: field_vroo_buro
-  Capacity: field_vroo_capa
