### ISSUE TITLE
Create new content type - Member Contribution

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#24]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Member Contribution | mcon | Title |   |   | node |   |   |  
  |   | Body | Default |   |   |   |   |  
  |   | Member Contribution Type | Taxonomy Term Reference |   |   |   |   |  
  |   | Track | Taxonomy Term Reference |   |   |   |   |  
  |   | Attribution Name | Plain Text |   |   |   |   |  
  |   | Attribution URL | Link |   |   |   |   |  
  |   | Document | Entity reference to docu |   |   |   |   |  
  |   | Video URL | Link |   |   |   |   |

**Comment by cjgratacos** [comment]
Done
