### ISSUE TITLE
Create new content type - Document

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#25]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Document | docu | Title | Default |   | node |   |   |  
  |   | Description | Plain text | 255 |   |   |   |  
  |   | File Upload |   |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by cjgratacos** [comment]
- Field Machine Name:
  -  Description: field_docu_desc
  -  File Upload: field_docu_fiup

**Comment by cjgratacos** [comment]
Done
