### ISSUE TITLE
Create new content type - Image Gallery

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#26]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Image Gallery | igal | Title | Default |   | node |   |   |  
  |   | Image |   |   |   |   |   |  
  |   | Teaser | Plain Text | 255 |   |   |   |  
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by ghost** [comment]
Content type created

**Comment by ghost** [comment]
Reviewed this content type and fixed the machine name of my image field to be compliant with the Relativity's way
