### ISSUE TITLE
Create new content type - System Documentation

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#27]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
System Documentation | sdoc | Title | Default |   | node |   |   |  
  |   | Body | Default |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by ghost** [comment]
Content type created
