### ISSUE TITLE
Number of values per field

### ISSUE THREAD

**Issue by ghost** [iribarne/broward-drupal#37]
Hi, 

I just created some content types and I have a question. 

I didn't see anywhere the settings I should add in regard to the number of values for each fields, so I supposed it was 1 and not unlimited.

Can someone tell me if I am right please ? Or if not, just can we update the google doc with the cardinalities per fields please :) 

Just in case, no fields are required too. Do we have any required fields ?

Thanks.

**Comment by jeppy64** [comment]
Good catch!, but we haven't defined that as of yet. Step 1 is to get all content types, fields and vocabularies into the system first. Then the next step will be to define ALL content type relationships. (hint--- some have been left out totally - some are incorrect).  This will be documented in the master spreadsheet. Then we can then wrap content types including relationships into field groups and assign cardnality. So step two is really perfecting relationships, cardnality, form display and entity display modes. Step 1 and Step two being perfected allows content editors to begin content loading and the dev team to move to Views based on the UX and Design comps.

**Comment by ghost** [comment]
Closing this issue as "answered." Issue will be referenced in next assignments per Jay's comment.
