### ISSUE TITLE
Add Users to GitHub Repo

### ISSUE THREAD

**Issue by ghost** [iribarne/broward-drupal#44]
## User Story

As a PM, I need the following documentation volunteers invited to the GitHub repo:
[Theydesignllc@llc@gmail.com](mailto:Theydesignllc@llc@gmail.com)
[Jmo@logisticsmaven.com](mailto:Jmo@logisticsmaven.com)

**Comment by ghost** [comment]
Please invite the other volunteers in addition to the volunteers in the first comment:
hlb1799@gmail.com
rebekahplee@gmail.com
rnorman489@hotmail.com
Ckosloff@hardwarealien.com

**Comment by iribarne** [comment]
To add users to the github repo, I need their github ids (i.e. not email addresses).

**Comment by iribarne** [comment]
I sent an email to the following email addresses to provide GitHub ids to have accounts created:
Jmo@logisticsmaven.com
hlb1799@gmail.com
rebekahplee@gmail.com
rnorman489@hotmail.com
Ckosloff@hardwarealien.com

The following email address is not valid: Theydesignllc@llc@gmail.com, so I did not send an email to that account.

**Comment by ghost** [comment]
@iribarne - that is a typo:
Corrected:Theydesignllc@gmail.com

**Comment by iribarne** [comment]
Added ckosloff and johnatasjmo to the github repo

**Comment by ghost** [comment]
Much obliged!

**Comment by iribarne** [comment]
Added dportier to the github repo
