### ISSUE TITLE
Volunteer Roles - Permissions

### ISSUE THREAD

**Issue by ghost** [iribarne/broward-drupal#6]
## Roles and Permissions

- [x] 1. **Create "Site Builder" Role:** Allows back-end dev volunteers to create content types and vocabularies. This role will not have full admin access. This role will not have access to *System* permissions.

- [x] 2. **Create "Content Editor" Role:** This role should be restricted to creating, editing and deleting content. This role will be for the end users who will create new events.

- [x] 3. **Add Back-End Volunteers as Site Builders**: For review, volunteers can be viewed [here](https://drive.google.com/open?id=19xLYK1kLdPSkMukgIctvH0WbN0OZ02EzlvanNfzIQR4).

4. **For Consideration & Discussion:** Different content editor roles. For example, "Content Editor 1" (CE1) and "Content Editor 2" (CE2) where CE1 can create, edit, delete, publish any content but CE2 can only create content but not publish - CE2 being like an "intern" role.

**Comment by ghost** [comment]
@iribarne & @jeppy64 - I submitted a new issue for creating two new user roles for the BDUG Relativity project.

**Comment by ghost** [comment]
Closing issue. If new roles need to be created, please open a new ticket/issue.

Thank you,

Beau

**Comment by shaal** [comment]
Site builders say they do not have the permission to add fields in any content type.

**Comment by ghost** [comment]
@jeppy64 - per @shaal's comment above ^^^

Requesting updated permissions to *Site Builder* role so fields can be added to content types.

Once confirmed, permissions will be granted.

**Comment by jeppy64** [comment]
Let's try it now.... I tweaked the site perms

**Comment by ghost** [comment]
Closing issue. Roles have been assigned and updated with proper permissions per @jeppy64.
