### ISSUE TITLE
Assign Content Types to Back-End Dev Volunteers

### ISSUE THREAD

**Issue by ghost** [iribarne/broward-drupal#7]
## Creating Content Types for the BDUG Relativity Project

- [x] Confirm with @iribarne that Issue #6 is complete

- [x] [Review the content types](https://drive.google.com/open?id=1rohrke25IiiPWZBjLnCluVt7yIeB_6ny9WocgbRT8w8) and assign equally to the back-end developer volunteers. Note at this stage of the build, we have 17 content types.

**Comment by ghost** [comment]
@shaal - the [team spreadsheet](https://docs.google.com/spreadsheets/d/19xLYK1kLdPSkMukgIctvH0WbN0OZ02EzlvanNfzIQR4/edit?usp=sharing) has been updated. Please note those who are confirmed **Site Builders** have the **Site Builder** role next to their name and have an active account on the [Relativity Event Management site](http://dev-relativity-event-management.pantheonsite.io/).

Regards,

Beau

**Comment by shaal** [comment]
All content types were assigned, with a deadline (milestone) for this coming Monday (October 2nd)
