### ISSUE TITLE
Assign Vocabularies/Terms

### ISSUE THREAD

**Issue by ghost** [iribarne/broward-drupal#8]
## Assign Vocabularies for the BDUG Relativity Project

- [x]  Confirm with @iribarne that Issue #6 is complete

- [x] [Review the vocabularies](https://docs.google.com/spreadsheets/d/1rohrke25IiiPWZBjLnCluVt7yIeB_6ny9WocgbRT8w8/edit?usp=sharing) and assign equally to the back-end developer volunteers. Note at this stage of the build, we have 7 vocabularies with anywhere from 4 - 6 terms per vocabulary.

**Comment by shaal** [comment]
All vocabularies and terms were assigned, with a deadline (milestone) for this coming Monday (October 2nd)
