### ISSUE TITLE
Create new content type - Organization

### ISSUE THREAD

**Issue by shaal** [iribarne/broward-drupal#9]
Content Type | Machine Name | Fields | Field Type | Max Character | Entity Type | Purpose | Menu Item? | Taxonomy
-- | -- | -- | -- | -- | -- | -- | -- | --
Organization | orga | Title | Default |   | node | Front Page |   |  
  |   | Body | Long text, formatted |   |   |   |   |

**Comment by ghost** [comment]
Content type created
